/**
 * 42videobricks
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Video from './Video';

/**
 * The Playlist model module.
 * @module model/Playlist
 * @version 1.2.0
 */
class Playlist {
    /**
     * Constructs a new <code>Playlist</code>.
     * Playlist Object
     * @alias module:model/Playlist
     * @param id {String} id of the playlist (null when adding a new video)
     */
    constructor(id) { 
        
        Playlist.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>Playlist</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Playlist} obj Optional instance to populate.
     * @return {module:model/Playlist} The populated <code>Playlist</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Playlist();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('children')) {
                obj['children'] = ApiClient.convertToType(data['children'], [Video]);
            }
            if (data.hasOwnProperty('ctime')) {
                obj['ctime'] = ApiClient.convertToType(data['ctime'], 'Number');
            }
            if (data.hasOwnProperty('mtime')) {
                obj['mtime'] = ApiClient.convertToType(data['mtime'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Playlist</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Playlist</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Playlist.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        if (data['children']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['children'])) {
                throw new Error("Expected the field `children` to be an array in the JSON data but got " + data['children']);
            }
            // validate the optional field `children` (array)
            for (const item of data['children']) {
                Video.validateJSON(item);
            };
        }

        return true;
    }


}

Playlist.RequiredProperties = ["id"];

/**
 * id of the playlist (null when adding a new video)
 * @member {String} id
 */
Playlist.prototype['id'] = undefined;

/**
 * name of the playlist
 * @member {String} name
 */
Playlist.prototype['name'] = undefined;

/**
 * description of the playlist
 * @member {String} description
 */
Playlist.prototype['description'] = undefined;

/**
 * ordered list of video in the playlist
 * @member {Array.<module:model/Video>} children
 */
Playlist.prototype['children'] = undefined;

/**
 * Creation date (timestamp)
 * @member {Number} ctime
 */
Playlist.prototype['ctime'] = undefined;

/**
 * Modification date (timestamp)
 * @member {Number} mtime
 */
Playlist.prototype['mtime'] = undefined;






export default Playlist;

