/**
 * 42videobricks
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VideoUploadInitResponse model module.
 * @module model/VideoUploadInitResponse
 * @version 1.1.2
 */
class VideoUploadInitResponse {
    /**
     * Constructs a new <code>VideoUploadInitResponse</code>.
     * Video Single Upload Init response object
     * @alias module:model/VideoUploadInitResponse
     */
    constructor() { 
        
        VideoUploadInitResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VideoUploadInitResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VideoUploadInitResponse} obj Optional instance to populate.
     * @return {module:model/VideoUploadInitResponse} The populated <code>VideoUploadInitResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VideoUploadInitResponse();

            if (data.hasOwnProperty('signedUrl')) {
                obj['signedUrl'] = ApiClient.convertToType(data['signedUrl'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VideoUploadInitResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VideoUploadInitResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['signedUrl'] && !(typeof data['signedUrl'] === 'string' || data['signedUrl'] instanceof String)) {
            throw new Error("Expected the field `signedUrl` to be a primitive type in the JSON string but got " + data['signedUrl']);
        }

        return true;
    }


}



/**
 * signed url
 * @member {String} signedUrl
 */
VideoUploadInitResponse.prototype['signedUrl'] = undefined;






export default VideoUploadInitResponse;

