/**
 * 42videobricks
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VideoMultipartUploadFinalizePartsInner model module.
 * @module model/VideoMultipartUploadFinalizePartsInner
 * @version 1.1.1
 */
class VideoMultipartUploadFinalizePartsInner {
    /**
     * Constructs a new <code>VideoMultipartUploadFinalizePartsInner</code>.
     * part signed url object
     * @alias module:model/VideoMultipartUploadFinalizePartsInner
     */
    constructor() { 
        
        VideoMultipartUploadFinalizePartsInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VideoMultipartUploadFinalizePartsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VideoMultipartUploadFinalizePartsInner} obj Optional instance to populate.
     * @return {module:model/VideoMultipartUploadFinalizePartsInner} The populated <code>VideoMultipartUploadFinalizePartsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VideoMultipartUploadFinalizePartsInner();

            if (data.hasOwnProperty('PartNumber')) {
                obj['PartNumber'] = ApiClient.convertToType(data['PartNumber'], 'Number');
            }
            if (data.hasOwnProperty('ETag')) {
                obj['ETag'] = ApiClient.convertToType(data['ETag'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VideoMultipartUploadFinalizePartsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VideoMultipartUploadFinalizePartsInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['ETag'] && !(typeof data['ETag'] === 'string' || data['ETag'] instanceof String)) {
            throw new Error("Expected the field `ETag` to be a primitive type in the JSON string but got " + data['ETag']);
        }

        return true;
    }


}



/**
 * part number
 * @member {Number} PartNumber
 */
VideoMultipartUploadFinalizePartsInner.prototype['PartNumber'] = undefined;

/**
 * part Etag
 * @member {String} ETag
 */
VideoMultipartUploadFinalizePartsInner.prototype['ETag'] = undefined;






export default VideoMultipartUploadFinalizePartsInner;

