/**
 * 42videobricks
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VideoMultipartUploadInit model module.
 * @module model/VideoMultipartUploadInit
 * @version 1.1
 */
class VideoMultipartUploadInit {
    /**
     * Constructs a new <code>VideoMultipartUploadInit</code>.
     * Video Mutlipart Upload Init
     * @alias module:model/VideoMultipartUploadInit
     * @param name {String} file name
     * @param size {Number} file size (in bits)
     */
    constructor(name, size) { 
        
        VideoMultipartUploadInit.initialize(this, name, size);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, size) { 
        obj['name'] = name;
        obj['size'] = size;
    }

    /**
     * Constructs a <code>VideoMultipartUploadInit</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VideoMultipartUploadInit} obj Optional instance to populate.
     * @return {module:model/VideoMultipartUploadInit} The populated <code>VideoMultipartUploadInit</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VideoMultipartUploadInit();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VideoMultipartUploadInit</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VideoMultipartUploadInit</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of VideoMultipartUploadInit.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}

VideoMultipartUploadInit.RequiredProperties = ["name", "size"];

/**
 * file name
 * @member {String} name
 */
VideoMultipartUploadInit.prototype['name'] = undefined;

/**
 * file size (in bits)
 * @member {Number} size
 */
VideoMultipartUploadInit.prototype['size'] = undefined;






export default VideoMultipartUploadInit;

