/**
 * 42videobricks
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WebhookProperties from './WebhookProperties';

/**
 * The Webhook model module.
 * @module model/Webhook
 * @version 1.1
 */
class Webhook {
    /**
     * Constructs a new <code>Webhook</code>.
     * Webhook Object
     * @alias module:model/Webhook
     * @implements module:model/WebhookProperties
     * @param url {String} Url of the application wich is receiving Notifications
     * @param eventType {Array.<module:model/Webhook.EventTypeEnum>} List of event to be notified:   * VIDEO_STATUS: Get Video object status modification notifications   Status values: REQUESTED, CREATED, TRANSCODING, AVAILABLE, DELETED   * VIDEO_TRANSCODING_PROGRESS: Get transcoding progression notifications
     * @param id {String} id of the webhook
     */
    constructor(url, eventType, id) { 
        WebhookProperties.initialize(this, url, eventType);
        Webhook.initialize(this, url, eventType, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, url, eventType, id) { 
        obj['url'] = url;
        obj['eventType'] = eventType;
        obj['id'] = id;
    }

    /**
     * Constructs a <code>Webhook</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Webhook} obj Optional instance to populate.
     * @return {module:model/Webhook} The populated <code>Webhook</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Webhook();
            WebhookProperties.constructFromObject(data, obj);

            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('eventType')) {
                obj['eventType'] = ApiClient.convertToType(data['eventType'], ['String']);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('ctime')) {
                obj['ctime'] = ApiClient.convertToType(data['ctime'], 'Number');
            }
            if (data.hasOwnProperty('mtime')) {
                obj['mtime'] = ApiClient.convertToType(data['mtime'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Webhook</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Webhook</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Webhook.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is a string
        if (data['token'] && !(typeof data['token'] === 'string' || data['token'] instanceof String)) {
            throw new Error("Expected the field `token` to be a primitive type in the JSON string but got " + data['token']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['eventType'])) {
            throw new Error("Expected the field `eventType` to be an array in the JSON data but got " + data['eventType']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }

        return true;
    }


}

Webhook.RequiredProperties = ["url", "eventType", "id"];

/**
 * Url of the application wich is receiving Notifications
 * @member {String} url
 */
Webhook.prototype['url'] = undefined;

/**
 * Optionnal Secret token to validate notifications. Sent with the request in the X-Vpass-Token HTTP header.
 * @member {String} token
 */
Webhook.prototype['token'] = undefined;

/**
 * List of event to be notified:   * VIDEO_STATUS: Get Video object status modification notifications   Status values: REQUESTED, CREATED, TRANSCODING, AVAILABLE, DELETED   * VIDEO_TRANSCODING_PROGRESS: Get transcoding progression notifications
 * @member {Array.<module:model/Webhook.EventTypeEnum>} eventType
 */
Webhook.prototype['eventType'] = undefined;

/**
 * id of the webhook
 * @member {String} id
 */
Webhook.prototype['id'] = undefined;

/**
 * Creation date (timestamp)
 * @member {Number} ctime
 */
Webhook.prototype['ctime'] = undefined;

/**
 * Modification date (timestamp)
 * @member {Number} mtime
 */
Webhook.prototype['mtime'] = undefined;


// Implement WebhookProperties interface:
/**
 * Url of the application wich is receiving Notifications
 * @member {String} url
 */
WebhookProperties.prototype['url'] = undefined;
/**
 * Optionnal Secret token to validate notifications. Sent with the request in the X-Vpass-Token HTTP header.
 * @member {String} token
 */
WebhookProperties.prototype['token'] = undefined;
/**
 * List of event to be notified:   * VIDEO_STATUS: Get Video object status modification notifications   Status values: REQUESTED, CREATED, TRANSCODING, AVAILABLE, DELETED   * VIDEO_TRANSCODING_PROGRESS: Get transcoding progression notifications
 * @member {Array.<module:model/WebhookProperties.EventTypeEnum>} eventType
 */
WebhookProperties.prototype['eventType'] = undefined;



/**
 * Allowed values for the <code>eventType</code> property.
 * @enum {String}
 * @readonly
 */
Webhook['EventTypeEnum'] = {

    /**
     * value: "VIDEO_STATUS"
     * @const
     */
    "STATUS": "VIDEO_STATUS",

    /**
     * value: "VIDEO_TRANSCODING_PROGRESS"
     * @const
     */
    "TRANSCODING_PROGRESS": "VIDEO_TRANSCODING_PROGRESS"
};



export default Webhook;

