/**
 * 42videobricks
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import DataVideoUsageList from '../model/DataVideoUsageList';
import Error from '../model/Error';

/**
* Data service.
* @module api/DataApi
* @version 1.2.0
*/
export default class DataApi {

    /**
    * Constructs a new DataApi. 
    * @alias module:api/DataApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getDataVideoUsage operation.
     * @callback module:api/DataApi~getDataVideoUsageCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DataVideoUsageList} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List Video Usage KPIs
     * Return the usage of the platform ressources.  By default, it returns monthly usage but unit (dayly|week|month) can be defined. For current period, usage is calculated until current time. Start and end dates can be also optionaly defined to filter results.
     * @param {Object} opts Optional parameters
     * @param {Number} [limit] Number of elements to return (default=10)
     * @param {Number} [offset] offset for pagination
     * @param {module:model/String} [interval] Period unit (day|week|month)
     * @param {String} [startDate] Start date for the period
     * @param {String} [endDate] End date for the period
     * @param {module:api/DataApi~getDataVideoUsageCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DataVideoUsageList}
     */
    getDataVideoUsage(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'limit': opts['limit'],
        'offset': opts['offset'],
        'interval': opts['interval'],
        'startDate': opts['startDate'],
        'endDate': opts['endDate']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['api_key'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DataVideoUsageList;
      return this.apiClient.callApi(
        '/data/videos/usage', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
