/**
 * 42videobricks
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.42videobricks);
  }
}(this, function(expect, 42videobricks) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new 42videobricks.DataVideoUsage();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DataVideoUsage', function() {
    it('should create an instance of DataVideoUsage', function() {
      // uncomment below and update the code to test DataVideoUsage
      //var instance = new 42videobricks.DataVideoUsage();
      //expect(instance).to.be.a(42videobricks.DataVideoUsage);
    });

    it('should have the property monthId (base name: "monthId")', function() {
      // uncomment below and update the code to test the property monthId
      //var instance = new 42videobricks.DataVideoUsage();
      //expect(instance).to.be();
    });

    it('should have the property transcoding (base name: "transcoding")', function() {
      // uncomment below and update the code to test the property transcoding
      //var instance = new 42videobricks.DataVideoUsage();
      //expect(instance).to.be();
    });

    it('should have the property hosting (base name: "hosting")', function() {
      // uncomment below and update the code to test the property hosting
      //var instance = new 42videobricks.DataVideoUsage();
      //expect(instance).to.be();
    });

    it('should have the property delivery (base name: "delivery")', function() {
      // uncomment below and update the code to test the property delivery
      //var instance = new 42videobricks.DataVideoUsage();
      //expect(instance).to.be();
    });

    it('should have the property drm (base name: "drm")', function() {
      // uncomment below and update the code to test the property drm
      //var instance = new 42videobricks.DataVideoUsage();
      //expect(instance).to.be();
    });

  });

}));
