/**
 * 42videobricks
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.42videobricks);
  }
}(this, function(expect, 42videobricks) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new 42videobricks.VideoMultipartUploadInit();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('VideoMultipartUploadInit', function() {
    it('should create an instance of VideoMultipartUploadInit', function() {
      // uncomment below and update the code to test VideoMultipartUploadInit
      //var instance = new 42videobricks.VideoMultipartUploadInit();
      //expect(instance).to.be.a(42videobricks.VideoMultipartUploadInit);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new 42videobricks.VideoMultipartUploadInit();
      //expect(instance).to.be();
    });

    it('should have the property size (base name: "size")', function() {
      // uncomment below and update the code to test the property size
      //var instance = new 42videobricks.VideoMultipartUploadInit();
      //expect(instance).to.be();
    });

  });

}));
