/**
 * 42videobricks
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import DataVideoUsage from './model/DataVideoUsage';
import DataVideoUsageList from './model/DataVideoUsageList';
import Error from './model/Error';
import Pagination from './model/Pagination';
import TagList from './model/TagList';
import Video from './model/Video';
import VideoAssets from './model/VideoAssets';
import VideoAttachment from './model/VideoAttachment';
import VideoAttachmentList from './model/VideoAttachmentList';
import VideoList from './model/VideoList';
import VideoMultipartUploadFinalize from './model/VideoMultipartUploadFinalize';
import VideoMultipartUploadFinalizePartsInner from './model/VideoMultipartUploadFinalizePartsInner';
import VideoMultipartUploadInit from './model/VideoMultipartUploadInit';
import VideoMultipartUploadInitResponse from './model/VideoMultipartUploadInitResponse';
import VideoMultipartUploadInitResponsePartsInner from './model/VideoMultipartUploadInitResponsePartsInner';
import VideoProperties from './model/VideoProperties';
import VideoUploadInitResponse from './model/VideoUploadInitResponse';
import Webhook from './model/Webhook';
import WebhookList from './model/WebhookList';
import WebhookProperties from './model/WebhookProperties';
import DataApi from './api/DataApi';
import TagsApi from './api/TagsApi';
import VideosApi from './api/VideosApi';
import WebhooksApi from './api/WebhooksApi';


/**
* Official Node.js client library for 42videobricks API..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var Api42Vb = require('index'); // See note below*.
* var xxxSvc = new Api42Vb.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new Api42Vb.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new Api42Vb.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new Api42Vb.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.1.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The DataVideoUsage model constructor.
     * @property {module:model/DataVideoUsage}
     */
    DataVideoUsage,

    /**
     * The DataVideoUsageList model constructor.
     * @property {module:model/DataVideoUsageList}
     */
    DataVideoUsageList,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The Pagination model constructor.
     * @property {module:model/Pagination}
     */
    Pagination,

    /**
     * The TagList model constructor.
     * @property {module:model/TagList}
     */
    TagList,

    /**
     * The Video model constructor.
     * @property {module:model/Video}
     */
    Video,

    /**
     * The VideoAssets model constructor.
     * @property {module:model/VideoAssets}
     */
    VideoAssets,

    /**
     * The VideoAttachment model constructor.
     * @property {module:model/VideoAttachment}
     */
    VideoAttachment,

    /**
     * The VideoAttachmentList model constructor.
     * @property {module:model/VideoAttachmentList}
     */
    VideoAttachmentList,

    /**
     * The VideoList model constructor.
     * @property {module:model/VideoList}
     */
    VideoList,

    /**
     * The VideoMultipartUploadFinalize model constructor.
     * @property {module:model/VideoMultipartUploadFinalize}
     */
    VideoMultipartUploadFinalize,

    /**
     * The VideoMultipartUploadFinalizePartsInner model constructor.
     * @property {module:model/VideoMultipartUploadFinalizePartsInner}
     */
    VideoMultipartUploadFinalizePartsInner,

    /**
     * The VideoMultipartUploadInit model constructor.
     * @property {module:model/VideoMultipartUploadInit}
     */
    VideoMultipartUploadInit,

    /**
     * The VideoMultipartUploadInitResponse model constructor.
     * @property {module:model/VideoMultipartUploadInitResponse}
     */
    VideoMultipartUploadInitResponse,

    /**
     * The VideoMultipartUploadInitResponsePartsInner model constructor.
     * @property {module:model/VideoMultipartUploadInitResponsePartsInner}
     */
    VideoMultipartUploadInitResponsePartsInner,

    /**
     * The VideoProperties model constructor.
     * @property {module:model/VideoProperties}
     */
    VideoProperties,

    /**
     * The VideoUploadInitResponse model constructor.
     * @property {module:model/VideoUploadInitResponse}
     */
    VideoUploadInitResponse,

    /**
     * The Webhook model constructor.
     * @property {module:model/Webhook}
     */
    Webhook,

    /**
     * The WebhookList model constructor.
     * @property {module:model/WebhookList}
     */
    WebhookList,

    /**
     * The WebhookProperties model constructor.
     * @property {module:model/WebhookProperties}
     */
    WebhookProperties,

    /**
    * The DataApi service constructor.
    * @property {module:api/DataApi}
    */
    DataApi,

    /**
    * The TagsApi service constructor.
    * @property {module:api/TagsApi}
    */
    TagsApi,

    /**
    * The VideosApi service constructor.
    * @property {module:api/VideosApi}
    */
    VideosApi,

    /**
    * The WebhooksApi service constructor.
    * @property {module:api/WebhooksApi}
    */
    WebhooksApi
};
